INSERT INTO `laborinsight-data.laborinsight.justjoinit_categories` (category_id, category_name)
VALUES
  (1, 'JavaScript'),
  (2, 'HTML'),
  (3, 'PHP'),
  (4, 'Ruby'),
  (5, 'Python'),
  (6, 'Java'),
  (7, '.NET'),
  (8, 'SCALA'),
  (9, 'C'),
  (10, 'Mobile'),
  (11, 'Testing'),
  (12, 'DevOps'),
  (13, 'Admin'),
  (14, 'UX/UI'),
  (15, 'PM'),
  (16, 'Game'),
  (17, 'Analytics'),
  (18, 'Security'),
  (19, 'Data'),
  (20, 'Go'),
  (21, 'Support'),
  (22, 'ERP'),
  (23, 'Architecture'),
  (24, 'Other'),
  (25, 'AI/ML');